- name: write in .bash_profile
  lineinfile: >
    dest=~/.bash_profile
    regexp="export HOMEBREW_CASK_OPTS="
    line='export HOMEBREW_CASK_OPTS="--appdir=/Applications"'

- name: install packages
  homebrew_cask: name={{ item }} state=installed
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items:
    # ide
    - visual-studio-code
    - intellij-idea-ce
    # browser
    - google-chrome
    - firefoxdeveloperedition
    # developer tool
    - gitkraken
    - iterm2
    - docker
    - sequel-pro

- name: docker - setup completion
  shell: >
    ln -s /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion /usr/local/etc/bash_completion.d/docker;
    ln -s /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion /usr/local/etc/bash_completion.d/docker-machine;
    ln -s /Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion /usr/local/etc/bash_completion.d/docker-compose;
