- name: write in .bash_profile
  lineinfile: >
    dest=~/.bash_profile
    regexp="export HOMEBREW_CASK_OPTS="
    line='export HOMEBREW_CASK_OPTS="--appdir=/Applications"'

- name: install packages
  homebrew_cask: name={{ item }} state=installed
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items:
    - visual-studio-code
    - gitkraken
    - iterm2
    - google-chrome
    - firefox
    - docker
