- name: brew tap
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: brew update
  homebrew: update_homebrew=yes

- name: install packages
  homebrew: name={{ item }} state=latest
  with_items:
    - git
    - tree
